"""
Django settings for group_chatting project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

# Generated by Django 3.2 on 2022-05-22 05:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ Class created to manage migrations """
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255)),
                ('bio', models.TextField()),
                ('stewardship',
                 models.ManyToManyField(blank=True,
                                        to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='user_profile',
                  to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
