# Generated by Django 3.2 on 2022-05-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_stewardship'),
        ('profiles', '0002_auto_20220521_0832'),
    ]

    operations = [
    ]
