# Generated by Django 3.2 on 2022-05-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20220521_1055'),
        ('profiles', '0003_merge_20220521_1121'),
    ]

    operations = [
    ]
