"""
Django settings for app configuration.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from django.apps import AppConfig


class HomeConfig(AppConfig):
    """ Class to configure app settings """
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'home'
