"""
Django settings for views.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from django.shortcuts import render
from django.contrib import messages
from django.views import View
from chat.models import Chat


# Create your views here.
class HomeView(View):
    """ Class to set home page view settings """
    def get(self, request, *args, **kwargs):
        """ Function to set home page view settings """
        chat = Chat.objects.all()
        return render(request, 'index.html', {'chat': chat})


class ContactView(View):
    """ Class to set contact page view settings """
    def get(self, request, *args, **kwargs):
        """ Function to set contact page view settings """
        chat = Chat.objects.all()
        return render(request, 'contact-us.html', {})
