"""
Django settings for views.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from django.shortcuts import render
from django.contrib import messages
from django.views import View
from chat.models import Chat
from .forms import ContactForm
from django.views.generic.edit import FormView


# Create your views here.
class HomeView(View):
    """ Class to set home page view settings """
    def get(self, request, *args, **kwargs):
        """ Function to set home page view settings """
        chat = Chat.objects.all()
        return render(request, 'index.html', {'chat': chat})


# class ContactView(View):
#     """ Class to set contact page view settings """
#     def get(self, request, *args, **kwargs):
#         """ Function to set contact page view settings """
#         chat = Chat.objects.all()
#         return render(request, 'contact-us.html', {})


class ContactView(FormView):
    template_name = 'contact-us.html'
    form_class = ContactForm
    # success_url = '/contact/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)
    