# Generated by Django 3.2 on 2022-05-21 05:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_logo'),
        ),
    ]
