# Generated by Django 3.2 on 2022-05-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images'),
        ),
    ]
