# Generated by Django 3.2 on 2022-05-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_chat_logo'),
        ('chat', '0005_alter_reaction_emoji'),
    ]

    operations = [
    ]
