"""
Django settings for admin.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.contrib import admin
from .models import Profile
# Register your models here.

# Register Profile model
admin.site.register(Profile)
